name: main
on:
  push:
    branches:
      - candidate
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm run dev
          wait-on: http://localhost:3000/
          config_file: cypress.json
          spec: "cypress/integration/**/*"
        env:
          CYPRESS_baseUrl: http://localhost:3000/
